# Generated by Django 3.2 on 2021-05-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('s_class', models.IntegerField()),
                ('s_city', models.CharField(max_length=255)),
                ('s_lover', models.CharField(max_length=255)),
            ],
        ),
    ]
